# WireGuard Server and Client Configuration

server:
  interface_name: vpn0
  port: 51820
  host_interface: eth0
  mtu: 1420
  public_endpoint: 5.75.189.129
  ipv4_dynamic: false
  ipv6_dynamic: false
  ipv4:
    enabled: true
    address: 10.0.1.2/24
    nat: true
    snat_ip: 59.95.64.1
  ipv6:
    enabled: true
    address: 2a01:4f8:1c1b:743c::12/80
    nat: true
    snat_ip: 2a01:4f4:1c1b:743c::1
clients:
  - name: phone14
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    persistent_keepalive: 26
    ipv4_address: 10.0.1.3/24
    ipv6_address: 2a01:4f8:1c1b:743c::13/80
  - name: laptop
    dns: 8.8.8.8, 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    persistent_keepalive: 25
    ipv4_address: 10.0.1.4/24
    ipv6_address: 2a01:4f8:1c1b:743c::14/80
  - name: phone13
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    ipv4_address: 10.0.1.6/24
    ipv6_address: 2a01:4f8:1c1b:743c::16/80
  - name: phone1344
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    ipv4_address: 10.0.1.5/24
    ipv6_address: 2a01:4f8:1c1b:743c::2/80
  - name: phone13444
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    ipv4_address: 10.0.1.7/24
    ipv6_address: 2a01:4f8:1c1b:743c::3/80
  - name: phone134443
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    ipv4_address: 10.0.1.8/24
    ipv6_address: 2a01:4f8:1c1b:743c::4/80
