# WireGuard Server and Client Configuration

server:
  interface_name: vpn0
  port: 51820
  host_interface: eth0
  mtu: 1420
  public_endpoint: 5.75.189.129
  ipv4_dynamic: true
  ipv6_dynamic: true
  ipv4:
    enabled: true
    address: 10.0.1.2/24
    nat: true
  ipv6:
    enabled: true
    address: 2a01:4f8:1c1b:743c::12/80
    nat: false

clients:
  - name: phone1
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    persistent_keepalive: 26

  - name: laptop
    dns: 8.8.8.8, 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    persistent_keepalive: 25

  - name: tablet
    dns: 9.9.9.9, 149.112.112.112
    mtu: 1200
    allowed_ips: 0.0.0.0/0, ::/0
    persistent_keepalive: 25
