# WireGuard Server and Client Configuration

local_peer:
  interface_name: vpn0
  port: 51820
  host_interface: eth0
  mtu: 1420
  public_endpoint:
  inet_dynamic: false
  inet6_dynamic: false
  inet:
    enabled: true
    gateway: 10.0.1.1/24
    nat44: true
    nat44_public_IP:
  inet6:
    enabled: true
    gateway: 200::1/64
    nat66: true
    nat66_public_IP:
remote_peer:
  - name: phone14
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    inet_address: 10.0.1.2/24
    inet6_address: 200::2/64
