# WireGuard Server and Client Configuration

local_peer:
  interface_name: vpn0
  port: 51820
  host_interface: eth0
  mtu: 1420
  public_endpoint: 5.75.189.129
  ipv4_dynamic: false
  ipv6_dynamic: false
  ipv4:
    enabled: true
    gateway: 10.0.1.2/24
    nat44: true
    nat44_public_IP: 59.95.64.1
  ipv6:
    enabled: true
    gateway: 2a01:4f8:1c1b:743c::12/80
    nat66: true
    nat66_public_IP: 2a01:4f4:1c1b:743c::1
remote_peer:
  - name: phone14
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    persistent_keepalive: 26
    ipv4_address: 10.0.1.3/24
    ipv6_address: 2a01:4f8:1c1b:743c::13/80
  - name: laptop
    dns: 8.8.8.8, 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
  - name: phone13
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
  - name: phone1344
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
  - name: phone13444
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
  - name: phone134443
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
