# WireGuard Server and Client Configuration

local_peer:
  interface_name: vpn0
  port: 51820
  host_interface: eth0
  mtu: 1420
  public_endpoint: 5.75.189.129
  ipv4_dynamic: false
  ipv6_dynamic: false
  ipv4:
    enabled: true
    gateway: 10.0.1.1/24
    nat44: true
    nat44_public_IP:
  ipv6:
    enabled: true
    gateway: 200::1/64
    nat66: true
    nat66_public_IP:
remote_peer:
  - name: phone14
    dns: 8.8.4.4
    mtu: 1420
    allowed_ips: 0.0.0.0/0, ::/0
    ipv4_address: 10.0.1.2/24
    ipv6_address: 200::2/64
